# Generated by Django 3.2.6 on 2021-08-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
