# Generated by Django 3.2.6 on 2021-08-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user_auth', '0002_rename_id_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
