# Generated by Django 3.2.6 on 2021-08-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_complete',
        ),
    ]
