# Generated by Django 3.2.6 on 2021-08-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_game_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='review',
        ),
    ]
